version: '2'
services:
   ########### portainer interface ########## 
  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - local
    restart: unless-stopped  
  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    command: --templates http://templates/templates.json -d /data
    networks:
      - local
    ports:
     - "9000:9000"
    restart: unless-stopped 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PT_DATA_DIR}:/data
  watchtower:
    image: centurylink/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped  
networks:
  local:
    driver: bridge